### ISSUE TITLE
Is there any plan to move from kubernetes release1.8 to release1.13 in vendor

### ISSUE THREAD

**Issue by ringtail** [kubernetes-incubator/cluster-capacity#104]
I found the kube-sheduler in vendor is very old. Is there any plan to move from kubernetes release1.8 to release1.13 in vendor

**Comment by aveshagarwal** [comment]
> I found the kube-sheduler in vendor is very old. Is there any plan to move from kubernetes release1.8 to release1.13 in vendor

Yes we have been thinking about it. Would you like to contribute?

**Comment by ringtail** [comment]
@aveshagarwal I am working on a project based on cluster-capacity. I can do that after that. Is there any weekly meeting that we can talk about the details and plan.

**Comment by ringtail** [comment]
@aveshagarwal https://github.com/ringtail/cluster-capacity/tree/release-1.12 I have merged cluster-capacity from release-1.8 to release-1.12. And it works well for now. I'll fix the left problems about unittests and vendor patch. Could you have a look at this branch?

**Comment by ingvagabund** [comment]
Resolved by https://github.com/kubernetes-incubator/cluster-capacity/pull/109
