### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ringtail** [kubernetes-incubator/cluster-capacity#107]
I want to rebase the code to kubernetes-1.13. Is there any reviewer to review?

**Comment by ingvagabund** [comment]
Wau, the latest rebase was done to kubernetes-1.9.0. @ringtail is 1.13 still your target version?

**Comment by ingvagabund** [comment]
We might even go for 1.15. Or, make a series starting at 1.13.

**Comment by ringtail** [comment]
@ingvagabund https://github.com/ringtail/cluster-capacity I have rebased to 1.12 and 1.13. I can rebase to 1.15 if necessary.

**Comment by ingvagabund** [comment]
@ingvagabund lemme rebase to 1.15. I need to again get familiar with the code.

**Comment by ingvagabund** [comment]
Rebase to 1.15.3 here: https://github.com/kubernetes-incubator/cluster-capacity/pull/108. Still testing though so far it looks good.

**Comment by ingvagabund** [comment]
@ringtail @gramidt PR is ready for review. Would you have time to give it a look?

**Comment by ingvagabund** [comment]
@ringtail is kube 1.13 a must for you? Or, will 1.15 work for you as well?

**Comment by ringtail** [comment]
> @ringtail @gramidt PR is ready for review. Would you have time to give it a look?

sure, but I am not a reviewer of this project. Maybe I can check out the code and give feedback in this issue.

**Comment by ringtail** [comment]
> @ringtail is kube 1.13 a must for you? Or, will 1.15 work for you as well?

For my case,1.12 and 1.13 is enough. I would like to move to 1.15 later.

**Comment by ingvagabund** [comment]
> sure, but I am not a reviewer of this project. Maybe I can check out the code and give feedback in this issue.

Atm, we are quite short on any reviewer of the project. Any testing/feedback would help.

**Comment by ingvagabund** [comment]
> For my case,1.12 and 1.13 is enough.

We might first rebase to 1.13 and then build my PR on top of that.

**Comment by ringtail** [comment]
> > For my case,1.12 and 1.13 is enough.
> 
> We might first rebase to 1.13 and then build my PR on top of that.

Thanks.

**Comment by gramidt** [comment]
> @ringtail @gramidt PR is ready for review. Would you have time to give it a look?

Unfortunately I'm also not a reviewer on the project, but would happy to help assist moving it forward. I will reach out to some colleagues to see if anyone can help.

**Comment by ingvagabund** [comment]
@ringtail can you open the rebase to 1.13 PR? I will review then.

**Comment by ingvagabund** [comment]
@ringtail ping

**Comment by ringtail** [comment]
> @ringtail ping

Hi @ingvagabund Sorry for a long delay. I will make up the code and submit this weekend.

**Comment by ingvagabund** [comment]
@ringtail ping

**Comment by ringtail** [comment]
> @ringtail ping

pong! Hey man. I have rebased the code to release-1.13.5. The PR is #109
