### ISSUE TITLE
Document required permissions to run in RBAC cluster

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#24]
If run as a pod on a cluster (k8s or openshift), we need to enumerate the minimal permissions required to run as part of deployment instructions.

@hodovska @aveshagarwal

**Comment by hodovska** [comment]
For k8s see https://github.com/kubernetes-incubator/cluster-capacity/blob/master/doc/RUN_IN_KUBERNETES.md
