### ISSUE TITLE
Ability to run as pod on cluster using in-cluster config

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#28]
For example, I want to be able to do the same as here...

https://github.com/kubernetes/kubernetes/pull/39006

**Comment by ingvagabund** [comment]
We already have that (or at least it was my impression) [1]. @hodovska can you confirm?

[1] https://github.com/kubernetes-incubator/cluster-capacity/blob/master/cmd/cluster-capacity/app/server.go#L153

**Comment by hodovska** [comment]
Yes, when kubeconfig and address of kube api server are not given in flags, cc tries to get in-cluster config. Maybe we should improve this approach to something more clear.

Should be inClusterConfig set as default with possibility to override the values from flags?

**Comment by ingvagabund** [comment]
> Should be inClusterConfig set as default with possibility to override the values from flags?

At best, this should be done automatically. The cc should recognize if it is running inside a pod or as a CLI.

**Comment by aveshagarwal** [comment]
I think this has already been addressed.
