### ISSUE TITLE
Think about reducing the number of supported admission controllers

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#29]
Given the evolving nature of admission control in k8s, I think we should evaluate reducing the number of admission controllers to a fixed set rather than the entire open ended list.

For reference see:
https://github.com/kubernetes/community/pull/132

The candidate list could be limited to things that default resources, and things that constrain resources.

1. LimitRanger
1. ResourceQuota

I am also not sure I would want to expose the full set of admission controllers at this time versus just being quota aware or not.

**Comment by derekwaynecarr** [comment]
Any of the other admission plugins that default toleration or node selector would be a good candidate as well

**Comment by ingvagabund** [comment]
All admissions taken into account are set in https://github.com/kubernetes-incubator/cluster-capacity/blob/master/config/apiserver.yaml#L7. If the supported set needs to get limited, it is a question of extending the validation of the configuration file and filtering out all non-supported admissions. Ending with failure or with warning stating all admissions that are skipped.

**Comment by ingvagabund** [comment]
Conc: Replace the configuration file apiserver flag with option with a list of admission pluggins

**Comment by ingvagabund** [comment]
Use ResourceQuota nad LimitRanges only at the moment

**Comment by aveshagarwal** [comment]
I think this is already fixed. Please reopen if it is still not addessed.
