### ISSUE TITLE
cluster capacity comes in two flavors

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#30]
kubernetes schedules two primary things:

1. pods to nodes
2. pvc to pv

thoughts about dividing the capacity command into two flavors to allow future expansion for clusters that do not have dynamic storage provisioning?

```
$ cluster-capacity compute // similar to current command
$ cluster-capacity storage // if we ever did something w/ pvc -> pv analysis?
```

**Comment by ingvagabund** [comment]
Given a nature of various analysis we can run over cluster resources, the ``cluster-capacity KEYWORD`` seems reasonable. Currently, only the cluster scheduler is part of analysis. PV and family is another area I would like to explore. For that, we need to extend beyond scheduler and include Kubelet and possibly other components or part(s) of components.

**Comment by derekwaynecarr** [comment]
```
$ cluster-capacity analyze compute --
$ cluster-capacity analyze storage --
```
