### ISSUE TITLE
Provide integration tests to be run as part of CI

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-incubator/cluster-capacity#31]
We need integration tests to verify the CC works.

**Assumptions**:
1) kubernetes cluster is already deployed

**The tests should consists of**:
1) building cc
2) running cc with various settings (pod without admissions, pod with admissions, ...)
3) running cc as a pod in the cluster
4) ...

**Magic command to run**:
```sh
make integration-test
```

**Comment by aveshagarwal** [comment]
Points 2 and 3 to me seem like end to end tests in cluster capacity context, isn't it? Any tests that require spawning a cluster would be end-to-end? Or what would be a end-to-end test?
