### ISSUE TITLE
update package names for this repo

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#32]
For example:
github.com/ingvagabund/cluster-capacity/pkg/api

Needs to become:
github.com/kubernetes-incubator/cluster-capacity/pkg/api

**Comment by derekwaynecarr** [comment]
Makefiles need to be updated as well....

**Comment by ingvagabund** [comment]
Done by https://github.com/kubernetes-incubator/cluster-capacity/commit/459a4440e7000b2e19705ffb25d39297a49cc6c3 and https://github.com/kubernetes-incubator/cluster-capacity/commit/cc5e37d7bda119d66c191906f1a493a303c9dcda
