### ISSUE TITLE
why specify --kubeconfig and --master

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#33]
I appear to have to provide both.

With a valid kubeconfig, I am getting:

```
$ ./cluster-capacity --kubeconfig=/home/decarr/.kube/config --podspec=examples/pod.yaml
(02:41:03 PM) decarr: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

I am not in-cluster.

**Comment by derekwaynecarr** [comment]
For example, I would expect the master to be pulled from the kubeconfig current cluster.

**Comment by aveshagarwal** [comment]
@derekwaynecarr Right, with --kubeconfig,  it should not ask for --master.

**Comment by aveshagarwal** [comment]
I think lets close it as it is fixed now. Please reopen if the issue still persists.
