### ISSUE TITLE
Improve clarity of command output

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#40]
```
$ ./cluster-capacity --kubeconfig=/home/decarr/.kube/config --podspec=examples/pod.yaml 
E0213 16:24:54.181990    4663 factory.go:583] Error scheduling cluster-capacity small-pod-26: pod (small-pod-26) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (1); retrying
The cluster can schedule 26 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-26) failed to fit in any node
```

The presence of the error text actually makes you think the command didn't work as expected.  Can we remove the error printed from the scheduler?

**Comment by ingvagabund** [comment]
If you mean ``E0213 16:24:54.181990    4663 factory.go:583] Error scheduling cluster-capacity small-pod-26: pod (small-pod-26) failed to fit in any node`` we can not. The error message comes from scheduler's logger.

**Comment by aveshagarwal** [comment]
Fixed by @derekwaynecarr in one of his PRs.
